### ISSUE TITLE
Use renovate to auto bump 

### ISSUE THREAD

**Issue by dgershman** [radiusmethod/homebrew-kxd#2]

**Comment by pjaudiomv** [comment]
done https://github.com/radiusmethod/homebrew-kxd/pull/4

**Comment by pjaudiomv** [comment]
damn didnt update version https://github.com/radiusmethod/homebrew-kxd/blob/main/Formula/kxd.rb#L2 I wonder if it wants a v in it

**Comment by dgershman** [comment]
you can add a helper as a comment.

**Comment by pjaudiomv** [comment]
I think it may work now

**Comment by pjaudiomv** [comment]
ugh no it wont, need some sort of helper comment like you said

**Comment by dgershman** [comment]
I did this for the Big Bang extension in Zarf. https://github.com/defenseunicorns/zarf/pull/1585/files

**Comment by pjaudiomv** [comment]
I think I did the things

**Comment by pjaudiomv** [comment]
https://github.com/radiusmethod/homebrew-kxd/pull/6/files

**Comment by pjaudiomv** [comment]
ok this should be resolved
